Coin_10 = 0
Coin_5 = 0
Coin_2 = 0
Coin_1 = 0
Change = int(input())
if Change >= 10 :
    Coin_10 = Change//10
    Change = Change-(Coin_10*10)
if Change >= 5 :
    Coin_5 = Change//5
    Change = Change-(Coin_5*5)
if Change >= 2 :
    Coin_2 = Change//2
    Change = Change-(Coin_2*2)
if Change >= 1 :
    Coin_1 = Change
    Change = Change-Coin_10
print ("Coins Used = ",Coin_10+Coin_5+Coin_2+Coin_1," Coins")
